[package]
name = "cmd-wrapped"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
regex = "1.5"
lazy_static = "1.4.0"
colored = "2.1.0"
num-traits = "0.2.17"
